from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
SKETCH_DIR = ROOT / "Examples" / "Arduino" / "12_Codex_Status"
IMAGE_DIR = SKETCH_DIR / "image"
OUTPUT_FILE = SKETCH_DIR / "codex_status_images.c"
STATES = ("work", "idle", "done", "error")
TARGET_WIDTH = 410
TARGET_HEIGHT = 160


def rgb565_bytes(image: Image.Image) -> bytes:
    data = bytearray()
    for red, green, blue in image.convert("RGB").getdata():
        value = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
        data.append(value & 0xFF)
        data.append((value >> 8) & 0xFF)
    return bytes(data)


def resize_for_panel(image: Image.Image) -> Image.Image:
    return ImageOps.fit(
        image.convert("RGB"),
        (TARGET_WIDTH, TARGET_HEIGHT),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )


def format_byte_array(data: bytes) -> str:
    lines = []
    for index in range(0, len(data), 16):
        chunk = data[index : index + 16]
        values = ",".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"  {values},")
    return "\n".join(lines)


def image_block(state: str) -> str:
    source = IMAGE_DIR / f"{state}.png"
    original = Image.open(source)
    resized = resize_for_panel(original)
    data = rgb565_bytes(resized)
    width, height = resized.size

    return f"""/* {state}.png: {original.width}x{original.height} -> {width}x{height}, RGB565 */
#ifndef LV_ATTRIBUTE_IMG_CODEX_IMG_{state.upper()}
#define LV_ATTRIBUTE_IMG_CODEX_IMG_{state.upper()}
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_CODEX_IMG_{state.upper()} uint8_t
codex_img_{state}_map[] = {{
  /* Pixel format: Red: 5 bit, Green: 6 bit, Blue: 5 bit */
{format_byte_array(data)}
}};

const lv_image_dsc_t codex_img_{state} = {{
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = LV_COLOR_FORMAT_RGB565,
  .header.flags = 0,
  .header.w = {width},
  .header.h = {height},
  .header.stride = {width * 2},
  .data_size = sizeof(codex_img_{state}_map),
  .data = codex_img_{state}_map,
}};
"""


def main() -> None:
    missing = [state for state in STATES if not (IMAGE_DIR / f"{state}.png").is_file()]
    if missing:
        raise FileNotFoundError(f"Missing status images: {', '.join(missing)}")

    body = "\n".join(image_block(state) for state in STATES)
    OUTPUT_FILE.write_text(
        f"""/* Auto-generated by tools/prepare_codex_status_images.py. */
#ifdef __has_include
  #if __has_include("lvgl.h")
    #ifndef LV_LVGL_H_INCLUDE_SIMPLE
      #define LV_LVGL_H_INCLUDE_SIMPLE
    #endif
  #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
  #include "lvgl.h"
#else
  #include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

{body}
""",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
